service: mercado-pago-service

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  createPreference:
    handler: createPreference.handler
    events:
      - http:
          path: create-preference
          method: post

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

  serverless-offline:
    httpPort: 3000
